inherit_gem:
  main_branch_shared_rubocop_config: config/rubocop.yml

AllCops:
  # RuboCop enforces rules depending on the oldest version of Ruby which
  # your project supports:
  TargetRubyVersion: 3.1
